# My Test coding Documents
#print ("hello world")
#print (int(1.23))
"""print ("Enter a value")
a=int(input())
print ("value of a =",a)
print ("Enter a value")
b=int(input())
print ("value of b =",b)
c=a+b
print ("value of c =",c)
print ("Enter a value")
a=float(input())
print ("value of a =",a)
print ("Enter a value")
b=int(input())
print ("value of b =",b)
c=a+b
print ("value of c =",c)
print("Raguraman")
print ("Enter a value")
a=str(input())
print ("value of a =",a)
print ("Enter a value")
b=str(input())
print ("value of b =",b)
c=(a+b)
print ("value of c =",int(c))"""